<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit31fb22b8c6dcd9f479e37e4f6774c44e
{
    public static $prefixLengthsPsr4 = array (
        'b' => 
        array (
            'braga\\tools\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'braga\\tools\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/braga',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit31fb22b8c6dcd9f479e37e4f6774c44e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit31fb22b8c6dcd9f479e37e4f6774c44e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
